## Due Dates

### D8, Q9 Due Monday 6/3
### Checkpoint 2 Due Friday 5/30
### A4 (Released this Friday) Due next Friday 6/10

## D8 Review

## Part 1

In [1]:
import pandas as pd

titan = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
titan.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
titan.shape

(891, 12)

### Finding the number of missing values in each column

In [ ]:
titan.isna().sum(axis = 0)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
titan.isnull().sum(axis = 0)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Dropping data where there's missing values for Age and Embarked

In [ ]:
titan = titan.dropna(subset = ['Age', 'Embarked'])

In [ ]:
titan.shape

(712, 12)

In [ ]:
titan

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
import numpy as np

In [ ]:
passenger_ids = np.arange(1, 892)
weights = np.random.randint(150, 251, size=891)
passenger_weight_df = pd.DataFrame({
    'PassengerId': passenger_ids,
    'Weight': weights
})

passenger_weight_df.head()

   PassengerId  Weight
0            1     241
1            2     161
2            3     199
3            4     203
4            5     245

###  Left joining Titanic dataset with Passenger Weight data

pd.merge in pandas is used to combine two dataframes based on common columns. It automatically merges the dataframes on all columns that both dataframes have in common.

Specifying how = 'left' performs a left join, meaning that the resulting dataframe include all rows from the left dataframe and the matched rows from the right dataframe. If there is no match, the right wide will contain NaN.

In [ ]:
titan_df = pd.merge(titan, passenger_weight_df, how="left")

In [ ]:
titan_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Weight
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,241
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,161
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,199
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,203
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,245

In this case, the common column is PassengerId, so the dataframes merged on PassengerId

### Checking how many different type of Cabin there is in the dataset

In [ ]:
titan_df['Cabin'].value_counts()

Cabin
G6             4
B96 B98        4
C23 C25 C27    4
F33            3
D              3
              ..
C91            1
C124           1
C32            1
E34            1
C148           1
Name: count, Length: 133, dtype: int64

### Limiting to just top 100 Cabins

In [ ]:
cabins = titan_df['Cabin'].value_counts()[:100].index.tolist()
temp = titan_df[titan_df['Cabin'].isin(cabins)]

In [ ]:
temp.shape

(150, 13)

## Part 2

In [ ]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add the target variable
df['species'] = pd.DataFrame(iris.target)

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

### Splitting into predictors (everything else) and outcome variable (species)

In [ ]:
x = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)']]
y = df['species']

### Splitting into 80% train and 20% test

For the purpose of this lab, do **not** use train_test_split from sklearn

In [ ]:
n_train = int(len(df)*0.8)
n_test = len(df) - n_train

In [ ]:
train_x = x[:n_train]
train_y = y[:n_train]
test_x = x[n_train:]
test_y = y[n_train:]

train_x is the predictors for the train data, test_x is the outcome for the train data

train_y is the predictors for the test data, test_y is the outcome for the test data

### Traininig a model

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_fscore_support

In [ ]:
def train_SVM(X,y, kernel = 'linear'):
    clf = SVC(kernel = kernel)
    clf.fit(X, y)

    return clf

Training on the train data

In [ ]:
iris_clf = train_SVM(train_x, train_y)

### Making Predictions

Making predictions on the train and test data

In [ ]:
predicted_train_y = iris_clf.predict(train_x)
predicted_test_y = iris_clf.predict(test_x)

## Part 3 - Model Assessment

### Classification report on the predictions generated from training data

In [ ]:
print(classification_report(train_y, predicted_train_y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      0.98      0.99        50
           2       0.95      1.00      0.98        20

    accuracy                           0.99       120
   macro avg       0.98      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

### Confusion Matrix on the predictions generated from training data

In [ ]:
print(confusion_matrix(train_y, predicted_train_y, sample_weight=None))

[[50  0  0]
 [ 0 49  1]
 [ 0  0 20]]